version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  backend:
    build:
      context: ./Backend 
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
